### PR TITLE
Feature/search page

### PR DESCRIPTION
**Pull request by alexgomez54**
adds ability to see a search page and query for available itineraries.

### CODE REVIEW

**Comment by jahanzebk** [comment]
how does arrival_date.present? and departure_date.present? check if the date range is valid? Shouldn't you be making sure the departure date is after the arrival date for it to be valid?

**Comment by jahanzebk** [comment]
Other than that 👍 👍

**Comment by jahanzebk** [comment]
Also, do we want to remove  app/views/itineraries/search.html.erb if we are showing search results in searches/show.html.erb?

**Comment by alexgomez54** [comment]
Rewrote validations and deleted unnecessary file.

**Pull request merged**
