### PR TITLE
Chore/remove type

### PR DESCRIPTION
**Pull request by alexgomez54**
_DEPENDS ON #6_

More cleanup of internals. Removes mentions of types from the app and redoes admin dashboard so that it works under new schema.

### CODE REVIEW

**Comment by jahanzebk** [comment]
why comment out so much of the index function in itineraries_controller.rb?

**Comment by alexgomez54** [comment]
I was thinking this could be placeholder for now since the queries are breaking so easily. We could handle proper searching in a future pull request. #8 gets us a bit closer to what we want.

**Comment by jahanzebk** [comment]
Alright, makes sense. Also, why remove user_test and test_helper files?

**Comment by alexgomez54** [comment]
These are the default test structures that come with Rails. But later on when we start doing testing we can use a more powerful framework called Rspec http://rspec.info/

**Comment by jahanzebk** [comment]
👍

**Pull request merged**
